apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mentoraone
  namespace: mentoraone
spec:
  rules:
    - host: mentoraone.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mentoraone
                port:
                  number: 80
