apiVersion: v1
kind: Service
metadata:
  name: mentoraone
  namespace: mentoraone
spec:
  type: NodePort
  selector:
    app: mentoraone
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
